# Troubleshooting

Science is hard, and getting computers to do what you want sometimes feels impossible.
While we can't address every problem, below are some suggestions that may help you move forward.
If you need more help, perhaps you might give an [Online Community] a chance?

### Share Galaxy History {-}

Many times people are more able and willing to help troubleshoot a problem when provided a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example){target="_blank"}.
One great feature of Galaxy is the ability to share your exact history through a custom URL.
See how to do this in Step 1 "Share via link" in the FAQ [Sharing your History](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_sharing.html){target="_blank"} 

```{r, echo=FALSE, fig.alt=''}
ottrpal::include_slide("https://docs.google.com/presentation/d/1fH9s5OLcRF5meZtFWTJe89RFvJSh125kdjhdqp5smqA/edit#slide=id.g302b08c5e6e_0_51")
```

### Galaxy Fundamentals {-}

Galaxy has many advanced features to help you scale an analysis from a single dataset to production level settings.
Learning more about these features can give you insight into what is going on under the hood and may help when troubleshooting problems.

- Lost among your histories? -- [Understanding Galaxy history system](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history/tutorial.html){target="_blank"}

- Datatset or cellection? -- [Using dataset collections](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html){target="_blank"}

- Trouble with workflows? -- [Creating, Editing and Importing Galaxy Workflows](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial.html){target="_blank"}

- Out of storage space? -- [Downloading and Deleting Data in Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/download-delete-data/tutorial.html){target="_blank"}
